import '@/styling/globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import Header from '@/layout/Header'
const jost = Jost({ subsets: ['latin'] })
import CardData from "@/components/Cards/CardData";
import { cardTypes } from "types";
import Card from "@/components/Cards/Card"
import CardList from "@/components/Cards/CardList";
export const metadata: Metadata = {
  title: 'Dominono',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { Pizzas, Drinks } = CardData
  const { classics, vegan } = Pizzas
  const { shakes, drinks } = Drinks

  return (
    <html lang="en">
      <body className={jost.className}><Header subItem={Pizzas}/>{children}</body>
    </html>
  )
}
